set -g escape-time 500
set -g focus-events off
set -g mouse on
set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind-key C-c new-window
bind-key C-a last-window
bind-key C-n next-window
bind-key C-p previous-window
bind-key C-d detach-client
bind-key C-t command-prompt -I "#W" "rename-window '%%'"

bind-key C-[ split-window -h
bind-key C-] split-window -v

